#!/usr/bin/env python3
"""Prompt evolution script generated by EvoSim Wizard.

Task: "You are an intelligent orchestrator. Route the user request to the correct spec
Run:  uv run python evolve_prompt.py
"""

from __future__ import annotations

import json
import logging
import os
import sys
import textwrap
import time
from pathlib import Path

from dotenv import load_dotenv
load_dotenv()

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(name)s %(levelname)s  %(message)s",
    datefmt="%H:%M:%S",
)


from prompture.prompt_evolver import (
    LLMBackend,
    LLMClient,
    PromptCandidate,
    PromptEvolverConfig,
)

from prompture.seed_loader import load_seed_template_config, penalties_to_proxy_checks

from prompture.strategies import (
    CompositeScorer,
    LLMJudge,
    NoEvalConfig,
    NoEvalPromptEvolver,
    ProblemType,
    ProxyCheck,
    ProxyMetricsScorer,
    Scorer,
    SelfConsistencyScorer,
)


# ── Task description ──────────────────────────────────
TASK_DESCRIPTION = """\"You are an intelligent orchestrator. Route the user request to the correct specialist agents in the appropriate sequence. Available Agents: authentication_agent, request_validation_agent, authorization_agent, user_information_retriever_agent, transaction_history_agent, balance_checking_agent, data_analysis_agent, risk_assessment_agent, duplicate_detection_agent, fraud_detection_agent, document_verification_agent, compliance_check_agent, cross_reference_agent, approval_workflow_agent, leave_approval_agent, refund_processing_agent, pricing_calculation_agent, policy_evaluation_agent, notification_agent, email_agent, report_generation_agent, audit_logging_agent, case_creation_agent, informational_queries_agent, troubleshooting_agent, recommendation_agent, intent_and_sentiment_extraction_agent\""""


BACKEND = LLMBackend.AZURE_OPENAI
MODEL = os.getenv("AZURE_OPENAI_DEPLOYMENT", "gpt-4.1")


_SEED_CONFIG = load_seed_template_config("agent_routing")
SEED_TEMPLATES = _SEED_CONFIG.seeds
_PENALTY_CHECKS = penalties_to_proxy_checks(_SEED_CONFIG.penalties)


TEST_INPUTS = [
    "Analyze the sentiment of the last 50 support tickets from client 'Acme Corp' and provide a summary of their satisfaction.",
    "Verify my address using the utility bill I uploaded.",
    "I need to complete KYC for my new account.",
    "Approve travel expense for $75.",
    "Create audit report of privileged user actions.",
    "Audit all high-value transactions from last week.",
    "Investigate the sudden spike in login failures from IP block 192.168.x.x. Check if these match any known botnets and block them if necessary.",
    "Run credit risk analysis for customer 77669.",
    "Process my employment verification documents.",
]


# Auto-generated mutation ideas — customise for your domain
DOMAIN_MUTATIONS = [
    "Add chain-of-thought reasoning",
    "Enforce strict output format",
    "Add error recovery instructions",
    "Inject few-shot examples",
    "Emphasise parameter extraction",
    "Add role-play framing",
    "Shorten to single paragraph",
    "Add 'think before answering' preamble",
    "Specify forbidden output patterns",
    "Add edge-case handling rules",
    "Rewrite in imperative voice",
    "Add output validation step",
    "For each agent, include a brief description of its purpose and when to use it",
    "Describe what each agent does so the routing decision is grounded in capability, not name",
]



# ── Scoring setup ─────────────────────────────────────────

def _is_valid_json(text: str) -> bool:
    try:
        json.loads(text)
        return True
    except (json.JSONDecodeError, ValueError):
        return False

def build_scorer(client: LLMClient) -> Scorer:
    """Build the scoring strategy for prompt evaluation."""
    judge = LLMJudge(rubric="You are evaluating an agent routing output for the task: \"You are an intelligent orchestrator. Route the user request to the correct specialist agents in the appropriate sequenc. Score 0-10 on these criteria: (1) Are the selected agents relevant to the user request? (2) Are they in a logical execution order? (3) Are unnecessary agents excluded (precision)? (4) Is the output valid, well-structured JSON?")
    consistency = SelfConsistencyScorer(num_samples=3)
    checks = [
        ProxyCheck(
            name="valid_json",
            check_fn=_is_valid_json,
            weight=3.0,
        ),
        ProxyCheck(
            name="has_sequence_or_array",
            check_fn=lambda x: '"sequence"' in x or (x.strip().startswith("[") and x.strip().endswith("]")),
            weight=2.0,
        ),
        ProxyCheck(
            name="contains_agent_name",
            check_fn=lambda x: "_agent" in x.lower() or "agent" in x.lower(),
            weight=2.0,
        ),
        ProxyCheck(
            name="no_verbose_explanation",
            check_fn=lambda x: len(x) < 1000 and x.count(".") < 10,
            weight=1.0,
        ),
        ProxyCheck(
            name="at_least_one_selection",
            check_fn=lambda x: len(x.strip()) > 10,
            weight=1.0,
        ),
    ]
    # Append penalty checks from seed template config
    checks.extend(_PENALTY_CHECKS)
    proxy = ProxyMetricsScorer(checks=checks)

    return CompositeScorer([
        (judge, 0.35),
        (consistency, 0.3),
        (proxy, 0.35),
    ])


# ── Main ─────────────────────────────────────────────────
if __name__ == "__main__":
    print()
    print("=" * 60)
    print("  Prompture Prompt Evolution")
    print("  Task: \"You are an intelligent orchestrator. Route the us...")
    print("=" * 60)
    print()

    config = NoEvalConfig(
        iterations=8,
        population_size=6,
        num_islands=3,
        problem_type=ProblemType.TOOL_ROUTING,
        adaptive_mutations=True,
        llm_mutation_rate=0.3,
        describe_entities=True,
        refine_after_splice=True,
        backend=BACKEND,
    )

    print("  Configuration:")
    print(f"    Generations:    {config.iterations}")
    print(f"    Population:     {config.population_size} per island")
    print(f"    Islands:        {config.num_islands}")
    print(f"    Seed templates: {len(SEED_TEMPLATES)}")
    print(f"    Test inputs:    {len(TEST_INPUTS)}")
    print(f"    Backend:        {BACKEND.value}")
    print(f"    Model:          {MODEL}")
    print()
    # Build LLM client and scorer
    from prompture.prompt_evolver import LLMClient, PromptEvolverConfig
    _llm_cfg = PromptEvolverConfig(
        backend=BACKEND,
        azure_deployment=MODEL,
        azure_use_rbac=True,
    )
    client = LLMClient(_llm_cfg)

    print("  Checking LLM backend...", end=" ")
    if client.is_available():
        print("OK")
    else:
        print("UNAVAILABLE (running in mock mode)")

    scorer = build_scorer(client)
    print(f"  Scorer: {scorer.name()}")

    # Run evolution
    evolver = NoEvalPromptEvolver(
        task_description=TASK_DESCRIPTION,
        test_inputs=TEST_INPUTS,
        scorer=scorer,
        config=config,
        seed_templates=SEED_TEMPLATES,
        custom_mutations=DOMAIN_MUTATIONS,
    )
    print()
    print("  " + "─" * 58)
    print("  Starting evolution...")
    print("  " + "─" * 58)
    start = time.time()
    result = evolver.run()
    elapsed = time.time() - start

    # Results
    print()
    print("=" * 60)
    print("  EVOLUTION COMPLETE")
    print("=" * 60)
    print(f"  Best fitness:      {result.best_score:.1%}")
    print(f"  Temperature:       {result.best_temperature:.3f}")
    print(f"  Top-p:             {result.best_top_p:.3f}")
    print(f"  Wall time:         {elapsed:.1f}s")
    print(f"  Total candidates:  {len(result.all_candidates)}")
    print(f"  Generations run:   {result.iterations_run}")
    print()
    print("  Best prompt:")
    print("  " + "─" * 58)
    for line in result.best_prompt.split("\n"):
        print(f"    {line}")
    print("  " + "─" * 58)

    # Save results
    out_path = Path("evolution_results.json")
    out_path.write_text(json.dumps({
        "task": TASK_DESCRIPTION,
        "best_prompt": result.best_prompt,
        "best_score": result.best_score,
        "best_temperature": result.best_temperature,
        "best_top_p": result.best_top_p,
        "wall_time": elapsed,
        "iterations": result.iterations_run,
    }, indent=2))
    print(f"\n  Results saved to {out_path}")

    # Export lineage tree
    lineage = result.lineage_json()
    lineage_path = Path("evolution_lineage.json")
    lineage_path.write_text(json.dumps(lineage, indent=2))
    print(f"  Lineage saved to {lineage_path} ({len(lineage)} candidates)")

    # LLM usage and cost report
    llm_client = evolver._client
    total_tokens = llm_client.total_input_tokens + llm_client.total_output_tokens
    # Azure OpenAI GPT-4.1 Global Standard pricing (per 1M tokens)
    COST_PER_1M_INPUT = 2.00
    COST_PER_1M_OUTPUT = 8.00
    input_cost = llm_client.total_input_tokens * COST_PER_1M_INPUT / 1_000_000
    output_cost = llm_client.total_output_tokens * COST_PER_1M_OUTPUT / 1_000_000
    total_cost = input_cost + output_cost
    print()
    print("  " + "─" * 58)
    print("  LLM USAGE REPORT")
    print("  " + "─" * 58)
    print(f"    Total LLM calls:     {llm_client.call_count}")
    print(f"    Input tokens:        {llm_client.total_input_tokens:,}")
    print(f"    Output tokens:       {llm_client.total_output_tokens:,}")
    print(f"    Total tokens:        {total_tokens:,}")
    print(f"    Est. cost (input):   ${input_cost:.4f}")
    print(f"    Est. cost (output):  ${output_cost:.4f}")
    print(f"    Est. total cost:     ${total_cost:.4f}")
    print(f"    Model:               {MODEL}")
    print(f"    Pricing:             ${COST_PER_1M_INPUT}/1M input, ${COST_PER_1M_OUTPUT}/1M output")
    print("  " + "─" * 58)

    print("  Done.")