#!/usr/bin/env python3
"""Prompt evolution script generated by EvoSim Wizard.

Task: ""You are an intelligent orchestrator. Route the user request to the correct spe
Run:  uv run python evolve_prompt.py
"""

from __future__ import annotations

import json
import os
import sys
import textwrap
import time
from pathlib import Path

# Load .env before any config reads os.environ
_env_path = Path(__file__).resolve().parent / ".env"
if _env_path.exists():
    for _line in _env_path.read_text().splitlines():
        _line = _line.strip()
        if _line and not _line.startswith("#") and "=" in _line:
            _key, _, _val = _line.partition("=")
            os.environ.setdefault(_key.strip(), _val.strip())

# Use managed identity (DefaultAzureCredential), not API keys
os.environ.setdefault("AZURE_OPENAI_USE_RBAC", "true")

from MutaGenAI.prompt_evolver import (
    LLMBackend,
    LLMClient,
    PromptCandidate,
    PromptEvolverConfig,
)

from MutaGenAI.strategies import (
    CompositeScorer,
    LLMJudge,
    NoEvalConfig,
    NoEvalPromptEvolver,
    ProblemType,
    ProxyCheck,
    ProxyMetricsScorer,
    Scorer,
    SelfConsistencyScorer,
)


# ── Task description ──────────────────────────────────
TASK_DESCRIPTION = """\"\"You are an intelligent orchestrator. Route the user request to the correct specialist agents in the appropriate sequence. Available Agents: authentication_agent, request_validation_agent, authorization_agent, user_information_retriever_agent, transaction_history_agent, balance_checking_agent, data_analysis_agent, risk_assessment_agent, duplicate_detection_agent, fraud_detection_agent, document_verification_agent, compliance_check_agent, cross_reference_agent, approval_workflow_agent, leave_approval_agent, refund_processing_agent, pricing_calculation_agent, policy_evaluation_agent, notification_agent, email_agent, report_generation_agent, audit_logging_agent, case_creation_agent, informational_queries_agent, troubleshooting_agent, recommendation_agent, intent_and_sentiment_extraction"""


BACKEND = LLMBackend.AZURE_OPENAI
MODEL = os.getenv("AZURE_OPENAI_DEPLOYMENT", "gpt-4.1")


SEED_TEMPLATES = [
    "You are an intelligent orchestrator. Route the user request to the correct specialist agents in the appropriate sequence. Available Agents: authentication_agent, request_validation_agent, authorization_agent, user_information_retriever_agent, transaction_history_agent, balance_checking_agent, data_analysis_agent, risk_assessment_agent, duplicate_detection_agent, fraud_detection_agent, document_verification_agent, compliance_check_agent, cross_reference_agent, approval_workflow_agent, leave_approval_agent, refund_processing_agent, pricing_calculation_agent, policy_evaluation_agent, notification_agent, email_agent, report_generation_agent, audit_logging_agent, case_creation_agent, informational_queries_agent, troubleshooting_agent, recommendation_agent, intent_and_sentiment_extraction_agent",
]


TEST_INPUTS = [
    "Analyze the sentiment of the last 50 support tickets from client 'Acme Corp' and provide a summary of their satisfaction.",
    "I need to complete KYC for my new account.",
    "Verify my address using the utility bill I uploaded.",
    "Create audit report of privileged user actions.",
    "Audit all high-value transactions from last week.",
    "Link my loyalty card to earn points on purchases.",
    "Recommend a credit card with travel benefits.",
    "I cancelled my subscription mid-month. Calculate the prorated refund and credit it back.",
    "Investigate the sudden spike in login failures from IP block 192.168.x.x. Check if these match any known botnets and block them if necessary.",
]


# Auto-generated mutation ideas — customise for your domain
DOMAIN_MUTATIONS = [
    "Add chain-of-thought reasoning",
    "Enforce strict output format",
    "Add error recovery instructions",
    "Inject few-shot examples",
    "Emphasise parameter extraction",
    "Add role-play framing",
    "Shorten to single paragraph",
    "Add 'think before answering' preamble",
    "Specify forbidden output patterns",
    "Add edge-case handling rules",
    "Rewrite in imperative voice",
    "Add output validation step",
]



# ── Scoring setup ─────────────────────────────────────────

def _is_valid_json(text: str) -> bool:
    try:
        json.loads(text)
        return True
    except (json.JSONDecodeError, ValueError):
        return False

def build_scorer(client: LLMClient) -> Scorer:
    """Build the scoring strategy for prompt evaluation."""
    judge = LLMJudge(rubric="Rate this output for the task: \"\"You are an intelligent orchestrator. Route the user request to the correct specialist agents in th. Score 0-10 on: correctness, format compliance, completeness.")
    consistency = SelfConsistencyScorer(num_samples=3)
    checks = [
        ProxyCheck(
            name="valid_json",
            check_fn=_is_valid_json,
            weight=2.0,
        ),
        ProxyCheck(
            name="has_function_name",
            check_fn=lambda x: any(c.isupper() for c in x),
            weight=1.5,
        ),
        ProxyCheck(
            name="bracket_format",
            check_fn=lambda x: '[' in x and '(' in x,
            weight=2.0,
        ),
        ProxyCheck(
            name="max_length",
            check_fn=lambda x: len(x) < 500,
            weight=1.0,
        ),
        ProxyCheck(
            name="no_explanation",
            check_fn=lambda x: len(x.splitlines()) <= 3,
            weight=1.0,
        ),
    ]
    proxy = ProxyMetricsScorer(checks=checks)

    return CompositeScorer([
        (judge, 0.3),
        (consistency, 0.25),
        (proxy, 0.2),
    ])


# ── Main ─────────────────────────────────────────────────
if __name__ == "__main__":
    print()
    print("=" * 60)
    print("  MutaGenAI Prompt Evolution")
    print("  Task: ""You are an intelligent orchestrator. Route the u...")
    print("=" * 60)
    print()

    config = NoEvalConfig(
        iterations=5,
        population_size=6,
        num_islands=3,
        problem_type=ProblemType.TOOL_ROUTING,
        backend=BACKEND,
    )

    print("  Configuration:")
    print(f"    Generations:    {config.iterations}")
    print(f"    Population:     {config.population_size} per island")
    print(f"    Islands:        {config.num_islands}")
    print(f"    Seed templates: {len(SEED_TEMPLATES)}")
    print(f"    Test inputs:    {len(TEST_INPUTS)}")
    print(f"    Backend:        {BACKEND.value}")
    print(f"    Model:          {MODEL}")
    print()

    # Build LLM client and scorer
    from MutaGenAI.prompt_evolver import LLMClient, PromptEvolverConfig
    _llm_cfg = PromptEvolverConfig(
        backend=BACKEND,
        azure_deployment=MODEL,
    )
    client = LLMClient(_llm_cfg)

    print("  Checking LLM backend...", end=" ")
    if client.is_available():
        print("OK")
    else:
        print("UNAVAILABLE (running in mock mode)")

    scorer = build_scorer(client)
    print(f"  Scorer: {scorer.name()}")

    # Run evolution
    evolver = NoEvalPromptEvolver(
        task_description=TASK_DESCRIPTION,
        test_inputs=TEST_INPUTS,
        scorer=scorer,
        config=config,
        seed_templates=SEED_TEMPLATES,
    )
    print()
    print("  " + "─" * 58)
    print("  Starting evolution...")
    print("  " + "─" * 58)
    start = time.time()
    result = evolver.run()
    elapsed = time.time() - start

    # Results
    print()
    print("=" * 60)
    print("  EVOLUTION COMPLETE")
    print("=" * 60)
    print(f"  Best fitness:      {result.best_score:.1%}")
    print(f"  Temperature:       {result.best_temperature:.3f}")
    print(f"  Top-p:             {result.best_top_p:.3f}")
    print(f"  Wall time:         {elapsed:.1f}s")
    print(f"  Total candidates:  {len(result.all_candidates)}")
    print(f"  Generations run:   {result.iterations_run}")
    print()
    print("  Best prompt:")
    print("  " + "─" * 58)
    for line in result.best_prompt.split("\n"):
        print(f"    {line}")
    print("  " + "─" * 58)

    # Save results
    out_path = Path("evolution_results.json")
    out_path.write_text(json.dumps({
        "task": TASK_DESCRIPTION,
        "best_prompt": result.best_prompt,
        "best_score": result.best_score,
        "best_temperature": result.best_temperature,
        "best_top_p": result.best_top_p,
        "wall_time": elapsed,
        "iterations": result.iterations_run,
    }, indent=2))
    print(f"\n  Results saved to {out_path}")

    # Export lineage tree
    lineage = result.lineage_json()
    lineage_path = Path("evolution_lineage.json")
    lineage_path.write_text(json.dumps(lineage, indent=2))
    print(f"  Lineage saved to {lineage_path} ({len(lineage)} candidates)")
    print("  Done.")